# Generated by Django 4.2.25 on 2025-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='intruder_image/%Y/%m/%d/'),
        ),
    ]
